

const info  = [
    {
        tag:'后台',
        people:[
            {
                position:"组长",
                name:'小红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'小蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组长",
                name:'小红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'小蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组长",
                name:'小红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'小蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            }


        ]
    },
    {
        tag:'前台',
        people:[
            {
                position:"组长",
                name:'大红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'大蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            }

        ]
    },
    {
        tag:'设计',
        people:[
            {
                position:"组长",
                name:'小红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'小蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'小灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            }


        ]
    },
    {
        tag:'产品',
        people:[
            {
                position:"组长",
                name:'大红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'大蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            }

        ]
    },
    {
        tag:'安卓',
        people:[
            {
                position:"组长",
                name:'大红',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"生命不息，奋斗不止"
            },
            {
                position:"组员",
                name:'大蓝',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大绿',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大粉',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            },
            {
                position:"组员",
                name:'大灰',
                photo:"https://avatars2.githubusercontent.com/u/22490787?s=460&v=4",
                intro:"黑夜给了我黑色的眼睛，我却用它寻找光明"
            }

        ]
    },



]
export default info